/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/k3OZs0LEmcO
 */
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { JSX, SVGProps } from "react"

export function Cancel() {
  const handleRedirectHome = () => {
    window.location.href = "/"
  }
  return (
    <div className="flex flex-col justify-center items-center gap-4 p-4 min-h-screen">
      <div className="flex flex-col items-center gap-2 text-center">
        <XCircleIcon className="h-12 w-12 text-red-500" />
        <div className="text-lg font-semibold">Compra cancelada</div>
        <div className="text-sm text-gray-500 dark:text-gray-400">
          Sua compra foi cancelada. Se você tiver alguma dúvida, entre em contato com o suporte.
        </div>
      </div>
      <div className="flex items-center gap-2">
        <Link className="flex-1" href="#">
          <Button onClick={handleRedirectHome} className="w-full" size="lg" variant="outline">
            Voltar
          </Button>
        </Link>
      </div>
    </div>
  )
}


function XCircleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m15 9-6 6" />
      <path d="m9 9 6 6" />
    </svg>
  )
}
