/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yPIPq0yLzTs
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Select } from "@/components/ui/select"
import Image from "next/image"

export default function CoursesPage() {
  return (
    <div className="flex flex-col min-h-screen">
      
      <main className="flex-1 bg-[#141414] text-white">
        <section className="py-24 px-4 md:px-8">
          <div className="container mx-auto max-w-3xl text-center">
            <h1 className="text-4xl font-bold mb-4">Seja Assinante Pro</h1>
            <p className="text-lg mb-8">Tenha acesso a todos os treinamentos da plataforma por apenas R$49.90 por mês.</p>
            <Button variant="teal">Assinatura Pro</Button>
          </div>
        </section>
        <section className="bg-[#222222] py-12 px-4 md:px-8">
          <div className="container mx-auto">
            <h2 className="text-2xl font-bold mb-6">Popular Courses</h2>
            <div className="flex gap-4 space-x-4 overflow-x-auto">
              <div className="flex-shrink-0 w-64">
                <Image
                  alt="Course Image"
                  className="rounded-lg mb-2"
                  height={144}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "256/144",
                    objectFit: "cover",
                  }}
                  width={256}
                />
                <h3 className="text-lg font-bold mb-1">Introduction to HTML and CSS</h3>
                <p className="text-gray-400 mb-2">$49.99</p>
                <Button variant="teal">Enroll</Button>
              </div>
              <div className="flex-shrink-0 w-64">
                <Image
                  alt="Course Image"
                  className="rounded-lg mb-2"
                  height={144}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "256/144",
                    objectFit: "cover",
                  }}
                  width={256}
                />
                <h3 className="text-lg font-bold mb-1">JavaScript for Beginners</h3>
                <p className="text-gray-400 mb-2">$59.99</p>
                <Button variant="teal">Enroll</Button>
              </div>
              <div className="flex-shrink-0 w-64">
                <Image
                  alt="Course Image"
                  className="rounded-lg mb-2"
                  height={144}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "256/144",
                    objectFit: "cover",
                  }}
                  width={256}
                />
                <h3 className="text-lg font-bold mb-1">React.js for Web Development</h3>
                <p className="text-gray-400 mb-2">$79.99</p>
                <Button variant="teal">Enroll</Button>
              </div>
              <div className="flex-shrink-0 w-64">
                <Image
                  alt="Course Image"
                  className="rounded-lg mb-2"
                  height={144}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "256/144",
                    objectFit: "cover",
                  }}
                  width={256}
                />
                <h3 className="text-lg font-bold mb-1">Full-Stack Development with Node.js</h3>
                <p className="text-gray-400 mb-2">$99.99</p>
                <Button variant="teal">Enroll</Button>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-[#141414] py-12 px-4 md:px-8">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-[200px_1fr] gap-8">
              <h2 className="text-2xl font-bold mb-6">All Courses</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="bg-[#222222] rounded-lg overflow-hidden">
                  <Image
                    alt="Course Image"
                    className="w-full h-48 object-cover"
                    height={216}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "384/216",
                      objectFit: "cover",
                    }}
                    width={384}
                  />
                  <div className="p-4">
                    <h3 className="text-lg font-bold mb-2">Introduction to HTML and CSS</h3>
                    <p className="text-gray-400 mb-4">$49.99</p>
                    <Button variant="teal">Enroll</Button>
                  </div>
                </div>
                <div className="bg-[#222222] rounded-lg overflow-hidden">
                  <Image
                    alt="Course Image"
                    className="w-full h-48 object-cover"
                    height={216}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "384/216",
                      objectFit: "cover",
                    }}
                    width={384}
                  />
                  <div className="p-4">
                    <h3 className="text-lg font-bold mb-2">JavaScript for Beginners</h3>
                    <p className="text-gray-400 mb-4">$59.99</p>
                    <Button variant="teal">Enroll</Button>
                  </div>
                </div>
                <div className="bg-[#222222] rounded-lg overflow-hidden">
                  <Image
                    alt="Course Image"
                    className="w-full h-48 object-cover"
                    height={216}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "384/216",
                      objectFit: "cover",
                    }}
                    width={384}
                  />
                  <div className="p-4">
                    <h3 className="text-lg font-bold mb-2">React.js for Web Development</h3>
                    <p className="text-gray-400 mb-4">$79.99</p>
                    <Button variant="teal">Enroll</Button>
                  </div>
                </div>
                <div className="bg-[#222222] rounded-lg overflow-hidden">
                  <Image
                    alt="Course Image"
                    className="w-full h-48 object-cover"
                    height={216}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "384/216",
                      objectFit: "cover",
                    }}
                    width={384}
                  />
                  <div className="p-4">
                    <h3 className="text-lg font-bold mb-2">Full-Stack Development with Node.js</h3>
                    <p className="text-gray-400 mb-4">$99.99</p>
                    <Button variant="teal">Enroll</Button>
                  </div>
                </div>
                <div className="bg-[#222222] rounded-lg overflow-hidden">
                  <Image
                    alt="Course Image"
                    className="w-full h-48 object-cover"
                    height={216}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "384/216",
                      objectFit: "cover",
                    }}
                    width={384}
                  />
                  <div className="p-4">
                    <h3 className="text-lg font-bold mb-2">Advanced CSS and Responsive Design</h3>
                    <p className="text-gray-400 mb-4">$69.99</p>
                    <Button variant="teal">Enroll</Button>
                  </div>
                </div>
                <div className="bg-[#222222] rounded-lg overflow-hidden">
                  <Image
                    alt="Course Image"
                    className="w-full h-48 object-cover"
                    height={216}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "384/216",
                      objectFit: "cover",
                    }}
                    width={384}
                  />
                  <div className="p-4">
                    <h3 className="text-lg font-bold mb-2">Mastering TypeScript for Enterprise Applications</h3>
                    <p className="text-gray-400 mb-4">$89.99</p>
                    <Button variant="teal">Enroll</Button>
                  </div>
                </div>
              </div>
            
          </div>
        </section>
      </main>
     
    </div>
  )
}
