/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0P1cjohNgIt
 */
import CheckoutButton from "./checkoutbutton"

export function Home() {
  return (
    <main className="flex-1 flex-col">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
        <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
          <div className="space-y-3">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
              The complete platform for building the Web
            </h1>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Give your team the toolkit to stop configuring and start innovating. Securely build, deploy, and scale the
              best web experiences.
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            <CheckoutButton/>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center gap-6 px-4 md:px-6 lg:gap-10">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Courses</h2>
            <p className="mx-auto max-w-[700px] text-gray-500/relaxed dark:text-gray-400">
              Learn how to build the web with our expert-led courses. From frontend design to backend databases,
              got you covered.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            <div className="space-y-2">
              <img
                alt="Image"
                className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                height="280"
                src="/placeholder.svg"
                width="500"
              />
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Building Beautiful Websites</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Learn the fundamentals of frontend design with our easy-to-follow course.
                </p>
              </div>
            </div>
            <div className="space-y-2">
              <img
                alt="Image"
                className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                height="280"
                src="/placeholder.svg"
                width="500"
              />
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Mastering the Jamstack</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Discover the power of the Jamstack with our hands-on tutorials.
                </p>
              </div>
            </div>
            <div className="space-y-2">
              <img
                alt="Image"
                className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                height="280"
                src="/placeholder.svg"
                width="500"
              />
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Serverless for Everyone</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Dive into serverless architecture with our step-by-step guides.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}
