/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GYg9TEGa5xp
 */
import { CardContent, Card } from "@/components/ui/card"
import CheckoutMonthtly from "./checkoutMonthtly"
import CheckoutYearly from "./checkoutYearly"
import { SessionValidationType } from "../../utils/sessionValidation"
import { getUserInfoAction } from "@/app/actions/getUserInfoAction";
async function getData(): Promise<SessionValidationType>{
  const data = await getUserInfoAction();
  return data; 
}
export async function PriceList() {
  const userInfos = await getData();
  return (
    <div id="assinar" className="w-full py-12 flex justify-center min-h-screen">
      <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-2 xl:gap-12">
        <div className="flex flex-col justify-center space-y-4">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter lg:text-4xl xl:text-5xl">Assinatura Pro</h1>
            <p className="max-w-[500px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Libere todo o potencial da sua criatividade com a Assinatura Pro. Tenha acesso a todos os cursos e recursos que vão elevar seus projetos a outro patamar.
            </p>
          </div>
        </div>
        <div className="mb-16 flex flex-col gap-4 min-[300px]:justify-end">
          <Card>
            <CardContent className="p-6 grid gap-4">
              <div className="flex items-center gap-4">
                <div className="text-3xl font-bold">R$49.90</div>
                <div className="text-sm font-semibold ml-auto shrink-0">/mês</div>
              </div>
              <div className="grid gap-0.5 text-sm leading-loose">
                <p className="text-base font-medium tracking-wide sm:text-lg">Cobrado mensalmente</p>
              </div>
              <CheckoutMonthtly products={userInfos.subscriptions}/>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6 grid gap-4">
              <div className="flex items-center gap-4">
                <div className="text-3xl font-bold">R$499</div>
                <div className="text-sm font-semibold ml-auto shrink-0">/anual</div>
              </div>
              <div className="grid gap-0.5 text-sm leading-loose">
                <p className="text-base font-medium tracking-wide">Economize R$89 com o plano anual</p>
              </div>
              <CheckoutYearly products={userInfos.subscriptions} />
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
